### ISSUE TITLE
#Principles KISS

### ISSUE THREAD

**Issue by Dr4gon** [echo75/graduation-project-johan-hedman#16]
@echo75 Looking at this 

`WatchList.vue`

```
.table-condensed > thead > tr > th,
.table-condensed > tbody > tr > th,
.table-condensed > tfoot > tr > th,
.table-condensed > thead > tr > td,
.table-condensed > tbody > tr > td,
.table-condensed > tfoot > tr > td {
  padding: 5px;
}
```

I'm wondering whether this would make it more readable 

```
.table-condensed > *> tr > th,
.table-condensed > *> tr > td{
  padding: 5px;
}
```

I'm not sure whether the * works. They don't have the example in the [reference](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator). I would test it, if your app would run in my codespace.

U have several of these examples in your code. Maybe worth a thought 😄

**Comment by echo75** [comment]
I refactored the code and could even do some other improvements in the CSS definitions. See buttons-definition
