### ISSUE TITLE
#Principles: Seperation of concerns  #DB.Design Using full movie object for watch/ed list

### ISSUE THREAD

**Issue by Dr4gon** [echo75/graduation-project-johan-hedman#23]
@echo75 A good question is: What would happen, if I populate my DB with 1.000.000 of a certain object?

`user.js`

```
  watch: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Movie', autopopulate: { maxDepth: 1 } }],
  watched: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Movie', autopopulate: { maxDepth: 1 } }],
```

Applying that million dollar question here my thesis is: It's either gonna be very very slow or crash altogether. 

The reason for that is that the app stores a full Movie Object in size and reference for every item on a watch/ed list. Which in fact isn't really necessary. The only thing u need is the Movie ID. If need be, you lazy load the data for the watch list from the Movie document. This will reduce the amount of data stored immensely on the de long run 😂

**Comment by Dr4gon** [comment]
*I just noticed that MongoDB might be clever about it. Can you check what the actual data in the DB looks like at the moment?

**Comment by johan-hedman** [comment]
It's just the movies object-id that is stored in the db, not the whole movie. The same thing for reviews
